version: '3'

networks:
  kafka-demo-py_default:
    external: true

services:

  producer:
    container_name: producer-api
    build: './producer_api'
    environment:
      HOST_KAFKA: broker
      HOST_APM: apm-server
      FLASK_ENV: development
    networks:
      - kafka-demo-py_default
    ports:
      - 8080:8080
    restart: always  

  consumer:
    container_name: consumer-api
    build: './consumer_api'
    environment:
      APP_PORT: 8084
      HOST_KAFKA: broker
      HOST_APM: apm-server
      FLASK_ENV: development
    networks:
      - kafka-demo-py_default
    ports:
      - 8084:8084
    restart: always
  
  stream-processor:
    container_name: stream_processor
    build: './stream_processor'
    environment:
      HOST_KAFKA: broker
      FLASK_ENV: development
    networks:
      - kafka-demo-py_default
    restart: always




